# Generated by Django 2.2.5 on 2019-09-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190912_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
