# Generated by Django 2.2.5 on 2019-09-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190912_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
