# Generated by Django 2.2.5 on 2019-09-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
